

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(685, 575)
        self.resourceTpyetable = QtWidgets.QTableWidget(parent=Form)
        self.resourceTpyetable.setGeometry(QtCore.QRect(60, 110, 561, 191))
        self.resourceTpyetable.setObjectName("resourceTpyetable")
        self.resourceTpyetable.setColumnCount(0)
        self.resourceTpyetable.setRowCount(0)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 20, 561, 80))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 30, 131, 31))
        self.label.setObjectName("label")
        self.s_resourceTpyeNameInpute = QtWidgets.QLineEdit(parent=self.groupBox)
        self.s_resourceTpyeNameInpute.setGeometry(QtCore.QRect(140, 30, 191, 31))
        self.s_resourceTpyeNameInpute.setObjectName("s_resourceTpyeNameInpute")
        self.searchBtn = QtWidgets.QPushButton(parent=self.groupBox)
        self.searchBtn.setGeometry(QtCore.QRect(400, 30, 81, 31))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/query.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchBtn.setIcon(icon)
        self.searchBtn.setObjectName("searchBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setGeometry(QtCore.QRect(60, 310, 561, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(40, 25, 54, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(270, 20, 91, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 41, 16))
        self.label_4.setObjectName("label_4")
        self.idinpute = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.idinpute.setGeometry(QtCore.QRect(80, 19, 91, 31))
        self.idinpute.setObjectName("idinpute")
        self.resourceNameTypeinput = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.resourceNameTypeinput.setGeometry(QtCore.QRect(360, 19, 131, 31))
        self.resourceNameTypeinput.setObjectName("resourceNameTypeinput")
        self.resourceTypeNameDesc = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.resourceTypeNameDesc.setGeometry(QtCore.QRect(80, 70, 411, 91))
        self.resourceTypeNameDesc.setObjectName("resourceTypeNameDesc")
        self.updatebtn = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.updatebtn.setGeometry(QtCore.QRect(120, 190, 75, 31))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/update.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.updatebtn.setIcon(icon1)
        self.updatebtn.setObjectName("updatebtn")
        self.delbtn = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.delbtn.setGeometry(QtCore.QRect(350, 190, 75, 31))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/del.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delbtn.setIcon(icon2)
        self.delbtn.setObjectName("delbtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "资源类别信息管理"))
        self.groupBox.setTitle(_translate("Form", "查询操作"))
        self.label.setText(_translate("Form", "资源类别名称："))
        self.searchBtn.setText(_translate("Form", "查询"))
        self.groupBox_2.setTitle(_translate("Form", "表单操作"))
        self.label_2.setText(_translate("Form", "编号："))
        self.label_3.setText(_translate("Form", "资源类别名称："))
        self.label_4.setText(_translate("Form", "描述："))
        self.updatebtn.setText(_translate("Form", "修改"))
        self.delbtn.setText(_translate("Form", "删除"))
